ls "C:\Cygwin\bin"
ls "C:\PROGRA~2\vim\vim74"
ls "C:\IBM\InformationServer\v11.3\jdk32\jre\bin"
ls "C:\IBM\InformationServer\v11.3\ASBNode\lib\cpp"
ls "C:\IBM\InformationServer\v11.3\ASBNode\apps\proxy\cpp\vc60\MT_dll\bin"
ls "C:\Program Files (x86)\MKS Toolkit\mksnt"
ls "C:\PROGRA~2\MKSTOO~1\bin64"
ls "C:\PROGRA~2\MKSTOO~1\bin"
ls "C:\PROGRA~2\MKSTOO~1\bin\X11"
ls "C:\PROGRA~2\MKSTOO~1\mksnt"
ls "C:\IBM\InformationServer\v8.7\ASBNode\apps\jre\bin\classic"
ls "C:\IBM\InformationServer\v8.7\ASBNode\lib\cpp"
ls "C:\IBM\InformationServer\v8.7\ASBNode\apps\proxy\cpp\vc60\MT_dll\bin"
ls "C:\Oracle\10gR2DS\jre\1.4.2\bin"
ls "C:\Oracle\10gR2DS\jre\1.4.2\bin\client"
ls "C:\Oracle\10gR2DS\BIN"
ls "C:\Oracle\10gR2DS\jlib"
ls "C:\Oracle\10gR2DS\jdk\jre\bin\client"
ls "C:\Oracle\10gR2DS\jdk\jre\bin"
ls "C:\Oracle\10gR2DS\jdk\jre\bin\classic"
ls "C:\Oracle\11gR202Client64bit\bin"
ls "C:\Oracle\11gR202Client32bit\bin"
ls "C:\Windows\system32"
ls "C:\Windows"
ls "C:\Windows\System32\Wbem"
ls "C:\Windows\System32\WindowsPowerShell\v1.0"
ls "C:\Program Files (x86)\Common Files\ACD Systems\EN"
ls "C:\Program Files (x86)\Common Files\ACD Systems"
ls "C:\Program Files\Intel\WiFi\bin"
ls "C:\Program Files\Common Files\Intel\WirelessCommon"
ls "C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn"
ls "C:\Program Files\Adobe\Adobe PDF iFilter 9 for 64-bit platforms\bin"
ls "C:\Program Files\Microsoft SQL Server\100\DTS\Binn"
ls "C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE"
ls "C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn"
ls "C:\Program Files\Microsoft SQL Server\100\Tools\Binn"
ls "C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies"
ls "C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn"
ls "C:\Windows\System32\WindowsPowerShell\v1.0"
ls "C:\Program Files\TortoiseSVN\bin"
ls "C:\Program Files\McAfee\Solidcore\Tools\GatherInfo"
ls "C:\Program Files\McAfee\Solidcore\Tools\Scanalyzer"
ls "C:\Program Files\McAfee\Solidcore"
ls "C:\Program Files\McAfee\Solidcore\Tools\ScGetCerts"
ls "C:\Program Files\McAfee\Tools\GatherInfo"
ls "C:\Program Files\McAfee\Tools\Scanalyzer"
ls "C:\Program Files\McAfee"
ls "C:\Program Files\McAfee\Tools\ScGetCerts"
